#!/usr/bin/env bash

# Run this script as root       # TODO: Delete every sudo, since we're root
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

# Colors (maybe someday)
# GREEN='\033[0;32m'
# CYAN='\033[0;35m'
# NC='\033[0m' # No Color

# Error out
die() {
    printf '%s\n' "$1" >&2
    exit 1
}

# Run as sudo but extend $PATH to have npm and node available
sudop() {
    sudo -u $(logname) bash -c "PATH=$PATH:/home/$(logname)/.n/bin/; $1"
}

# Run as user
userdo() {
    sudo -u $(logname) $1
}

# Usage info
# TODO: add --purge to also uninstall every install software
show_help() {
cat << EOF
Usage: ${0##*/} [OPTIONS...] [-n DOMNAME] [-p PORTNUM] [-e EMAIL]
Setup everything to deploy a website.

     -h, --help             display this help menu
     -n, --name DOMNAME     pass the name of the domain you want to use
     -p, --port PORTNUM     pass the port you'll host your website on
     -s, --secure           enable the ssl certificate using certbot
     -e, --email EMAIL      pass the email for the ssl certificate for registration and recovery contact
     -a, --autorenew        schedule automatic renewal of the certificate using crontab
     -d, --delete           undo everything wdt has done for a specified domain
EOF
}

# Initialize all the option variables.
# This ensures we are not contaminated by variables from the environment.
name=
port=
email=
enable_ssl=false
autorenew_ssl=false
delete_domain=false

while :; do
    case $1 in
        -h|-\?|--help)
            show_help    # Display a usage synopsis.
            exit
            ;;
        -n|--name)       # Takes an option argument; ensure it has been specified.
            if [ "$2" ]; then
                name=$2
                shift
            else
                die 'ERROR: "--name" requires a non-empty option argument.'
            fi
            ;;
        --name=?*)
            name=${1#*=} # Delete everything up to "=" and assign the remainder.
            ;;
        --name=)         # Handle the case of an empty --name=
            die 'ERROR: "--name" requires a non-empty option argument.'
            ;;
        -p|--port)       # Takes an option argument; ensure it has been specified.
            if [ "$2" ]; then
                port=$2
                shift
            else
                die 'ERROR: "--port" requires a non-empty option argument.'
            fi
            ;;
        --port=?*)
            port=${1#*=} # Delete everything up to "=" and assign the remainder.
            ;;
        --port=)         # Handle the case of an empty --name=
            die 'ERROR: "--port" requires a non-empty option argument.'
            ;;
        -e|--email)       # Takes an option argument; ensure it has been specified.
            if [ "$2" ]; then
                email=$2
                shift
            else
                die 'ERROR: "--email" requires a non-empty option argument.'
            fi
            ;;
        --email=?*)
            email=${1#*=} # Delete everything up to "=" and assign the remainder.
            ;;
        --email=)         # Handle the case of an empty --name=
            die 'ERROR: "--email" requires a non-empty option argument.'
            ;;
        -s|--secure)
            enable_ssl=true
            ;;
        -a|--autorenew)
            autorenew_ssl=true
            ;;
        -d|--delete)
            delete_domain=true
            ;;
        --)              # End of all options.
            shift
            break
            ;;
        -?*)
            # printf 'WARNING\: Unknown option (ignored): %s\n' "$1" >&2
            echo -e "ERROR: Invalid option -- \"$1\". Try \"wdt --help\" for more information."
            exit 1
            ;;
        *)               # Default case: No more options, so break out of the loop.
            break
    esac
    shift # this makes $1 = $2, $2 = $3, etc...
done


# Rest of the program here.
# If there are input files (for example) that follow the options, they
# will remain in the "$@" positional parameters.
# TODO: if there's still $1, assing it to $name

if $delete_domain; then

    if [ ! "$name" ]; then
        die 'ERROR: Please provide the DOMAIN to delete.'
    fi

    read -p "Are you sure you want to delete $name? [y|n] " -n 1 -r
    echo    # (optional) move to a new line
    if [[ $REPLY =~ ^[Yy]$ ]]; then

        if [ -f /etc/nginx/sites-available/$name ]; then
            echo -n "Deleting /etc/nginx/sites-available/$name... "
            sudo rm /etc/nginx/sites-available/$name
            echo "Done"
        else
            die "ERROR: $name entry not found."
        fi
        # -L check if there is a symlink, no matter broken or not
        if [ -L /etc/nginx/sites-enabled/$name ]; then
            echo -n "Deleting the symlink /etc/nginx/sites-enabled/$name... "
            sudo rm /etc/nginx/sites-enabled/$name
            echo "Done"
        fi
        if [ -d /var/www/$name ]; then
            echo -n "Deleting /var/www/$name... "
            sudo rm -r /var/www/$name
            echo "Done"
        fi
        sudo systemctl restart nginx

        # check if ssl certificate exists
        if [[ $(sudo certbot certificates 2> /dev/null) == *"$name"* ]]; then
            echo -n "Deleting the SSL certificate for $name... "
            sudo certbot delete --cert-name $name &> /dev/null
            echo "Done"
        fi

        # delete the cron job if it exists
        tmpfile=$(userdo mktemp)
        crontab -u $(logname) -l > $tmpfile
        sed -i "/certbot renew --quiet/d" $tmpfile
        crontab -u $(logname) $tmpfile && rm -f $tmpfile

        echo "The setup for $name was successfully deleted."
        exit
    else
        exit 0
    fi
fi

# if the necessary arguments are missing, error out
if [ ! "$name" ] || [ ! "$port" ]; then
    die 'ERROR: Please provide both the DOMAIN and the PORT. Try "wdt --help" for more information.'
elif $enable_ssl && [ ! "$email" ]; then
    die 'ERROR: Please provide the EMAIL to connect to the certificate for registration and recovery contact.'
fi

# ---------------------------- Installing stuff ---------------------------
# Install nodejs
if [ ! -d ~/.n ]; then
    echo -n "[nodejs]: Installing n version manager with node.js LTS... "
    curl -sL https://git.io/n-install | N_PREFIX=~/.n bash -s -- -q -n
    # fix the ownership problem
    sudo chown -R $(logname):$(logname) /home/$(logname)/.n
    echo "Done"
else
    echo "[nodejs]: Node is already installed"
fi

# Install pm2
if [ ! -f /home/$(logname)/.n/bin/pm2 ]; then
    echo -n "[pm2]: Installing pm2, a process manager for node.js... "
    # make sudo use $PATH instead of $SECURE_PATH, otherwise npm won't work
    sudop "npm install --global pm2 &> /dev/null"
    echo "Done"
else
    echo "[pm2]: PM2 process manager is already installed"
fi

# Install ufw
if [ ! -f /usr/sbin/ufw ]; then
    echo -n "[ufw]: Installing ufw -- the Uncomplicated Firewall... "
    sudo apt install ufw -y > /dev/null
    echo "Done"
else
    echo "[ufw]: Uncomplicated Firewall is already installed"
fi

# Install nginx
if [ ! -f /usr/sbin/nginx ]; then
    echo -n "[nginx]: Installing nginx... "
    sudo apt install nginx -y > /dev/null
    echo "Done"
else
    echo "[nginx]: Nginx is already installed"
fi

# ---------------------------- Actual commands ----------------------------
# npm install part
if [ ! -f ./package.json ]; then
    echo -n "[npm]: Initializing npm and installing Express.js... "
    sudop "npm init -y > /dev/null"
    sudop "npm install express &> /dev/null"
    echo "Done"
elif [ ! -d ./node_modules/express ]; then
    echo -n "[npm]: Installing Express.js... "
    sudop "npm install express &> /dev/null"
    echo "Done"
fi

# UFW
# check if it's german or english language to get the correct ufw status info
if [[ $(locale | grep LANG | cut -d= -f2 | cut -d_ -f1) == *"de"* ]]; then
    ufwstatus="Inaktiv"
elif [[ $(locale | grep LANG | cut -d= -f2 | cut -d_ -f1) == *"en"* ]]; then
    ufwstatus="inactive"
fi
# make sure firewall is enabled and allows ssh, http and https
if sudo ufw status | grep -qw $ufwstatus; then
    echo -n "[ufw]: Enabling ufw and allowing ssh (22), http (80) and https (443)... "
    sudo ufw enable > /dev/null
    sudo ufw allow ssh > /dev/null
    sudo ufw allow http > /dev/null
    sudo ufw allow https > /dev/null
    echo "Done"
else
    echo -n "[ufw]: Firewall is enabled. Allowing ssh (22), http (80) and https (443)... "
    sudo ufw allow ssh > /dev/null
    sudo ufw allow http > /dev/null
    sudo ufw allow https > /dev/null
    echo "Done"
fi

# Nginx part
if [ ! -d /var/www/$name/html ]; then

    ####### optional start #######
    # This parts creates the domain folder in /var/www. This isn't necessary,
    # if the user will not store files there. This is still made to do it the
    # correct way and allow user to change their mind and use this folder later
    #######

    # create the directories for the site
    sudo mkdir -p /var/www/$name/html
    echo "Creating a directory /var/www/$name/html... "
    # assing the correct ownership
    # using $(logname) allows to force run this script with sudo and still get the username
    sudo chown -R $(logname):$(logname) /var/www/$name/html
    # make permissions of our web roots are correct
    sudo chmod -R 755 /var/www
    # creating sample page for the site
    echo "Adding a sample index.html to /var/www/$name/html... "
    index_html_data="<html>\n\t<head>\n\t\t<title> Welcome to $name! </title>\n\t</head>\n\t<body>\n\t\t<h1> Success! The $name server block is working! </h1>\n\t</body>\n</html>"
    echo -e $index_html_data > /var/www/$name/html/index.html
    ####### optional end #######

    # creating Server Block Files for Each Domain
    echo "Creating /etc/nginx/sites-available/$name and adding the configuration to redirect to port $port... "
    nginx_sites_available_file_data="# Virtual Host configuration for $name\n#\nserver {\n\tlisten 80;\n\tlisten [::]:80;\n\n\tserver_name $name www.$name;\n\n\troot /var/www/$name/html;\n\tindex index.html index.htm index.nginx-debian.html;\n\n\tlocation / {\n\t\tproxy_pass http://localhost:$port; # whatever port your app runs on\n\t\tproxy_http_version 1.1;\n\t\tproxy_set_header Upgrade \$http_upgrade;\n\t\tproxy_set_header Connection 'upgrade';\n\t\tproxy_set_header Host \$host;\n\t\tproxy_cache_bypass \$http_upgrade;\n\t}\n}"
    # create new server file and correct it's permissions and ownership
    echo -e $nginx_sites_available_file_data > $name
    sudo mv $name /etc/nginx/sites-available/
    sudo chown -R root:root /etc/nginx/sites-available/$name
    sudo chmod 644 /etc/nginx/sites-available/$name
    # create a symlink to sites-enabled
    echo "Adding a symlink from /etc/nginx/sites-enabled/$name to /etc/nginx/sites-available/$name... "
    sudo ln -s /etc/nginx/sites-available/$name /etc/nginx/sites-enabled/
    # uncomment one line in order to avoid a possible hash bucket memory problem that can arise from adding additional server names
    sudo sed -i "s|# server_names_hash_bucket_size 64;|server_names_hash_bucket_size 64;|g" /etc/nginx/nginx.conf
    # restart nginx
    echo -n "Restarting nginx... "
    sudo systemctl restart nginx
    echo "Done"
fi

# Certbot part
if $enable_ssl; then

    # Install certbot with nginx extension
    if [ ! -f /usr/bin/certbot ]; then
        echo -n "[certbot]: Installing Certbot from Let's Encrypt with the nginx plugin... "
        sudo apt install python3-certbot-nginx -y > /dev/null
        echo "Done"
    elif [ ! -d /usr/lib/python3/dist-packages/certbot_nginx ]; then
        echo -n "[certbot]: Installing the nginx plugin for certbot... "
        sudo apt install python3-certbot-nginx -y > /dev/null
        echo "Done"
    else
        echo "[certbot]: Certbot with nginx plugin is already installed"
    fi

    # Enable SSL
    echo -n "[certbot]: Installing the certificate for $name... "
    sudo certbot --nginx -d $name -d www.$name --email $email --agree-tos --no-eff-email --redirect &> /dev/null
    echo "Done"
fi

# Crontab part
if $autorenew_ssl; then
    echo -n "Creating a cron job for certbot to renew the certificate... "
    # create a tempfile
    tmpfile=$(userdo mktemp)
    # write out current crontab
    crontab -u $(logname) -l > $tmpfile
    # echo new cron into cron file
    echo "0 5 * * * /usr/bin/certbot renew --quiet" >> $tmpfile
    # install new cron file
    crontab -u $(logname) $tmpfile && rm -f $tmpfile
    echo "Done"
fi

echo "The setup for $name is complete. Use \"pm2 start app.js\" to start your app.js."
