#!/usr/bin/env bash

# name="melkumyan-armen.com"
# port=5000

die() {
    printf '%s\n' "$1" >&2
    exit 1
}

# Usage info
show_help() {
cat << EOF
Usage: ${0##*/} [-hsa] [-n DOMNAME] [-p PORTNUM]
Setup everything to deploy a website.

     -h, --help             display this help menu
     -n, --name DOMNAME     pass the name of the domain you want to use
     -p, --port PORTNUM     pass the port you'll host your website on
     -s, --secure           enable the ssl certificate using certbot
     -a, --autorenew        schedule automatic renewal of the certificate using crontab
EOF
}

# Initialize all the option variables.
# This ensures we are not contaminated by variables from the environment.
name=
port=
enable_ssl=false
autorenew_ssl=false

while :; do
    case $1 in
        -h|-\?|--help)
            show_help    # Display a usage synopsis.
            exit
            ;;
        -n|--name)       # Takes an option argument; ensure it has been specified.
            if [ "$2" ]; then
                name=$2
                shift
            else
                die 'ERROR: "--name" requires a non-empty option argument.'
            fi
            ;;
        --name=?*)
            name=${1#*=} # Delete everything up to "=" and assign the remainder.
            ;;
        --name=)         # Handle the case of an empty --name=
            die 'ERROR: "--name" requires a non-empty option argument.'
            ;;
        -p|--port)       # Takes an option argument; ensure it has been specified.
            if [ "$2" ]; then
                port=$2
                shift
            else
                die 'ERROR: "--port" requires a non-empty option argument.'
            fi
            ;;
        --port=?*)
            port=${1#*=} # Delete everything up to "=" and assign the remainder.
            ;;
        --port=)         # Handle the case of an empty --name=
            die 'ERROR: "--port" requires a non-empty option argument.'
            ;;
        -s|--secure)
            enable_ssl=true
            ;;
        -a|--autorenew)
            autorenew_ssl=true
            ;;
        --)              # End of all options.
            shift
            break
            ;;
        -?*)
            printf 'WARNING: Unknown option (ignored): %s\n' "$1" >&2
            ;;
        *)               # Default case: No more options, so break out of the loop.
            break
    esac
    shift # this makes $1 = $2, $2 = $3, etc...
done


# Rest of the program here.
# If there are input files (for example) that follow the options, they
# will remain in the "$@" positional parameters.

# if --name and --port were not provided, error out
if [ ! "$name" ] || [ ! "$port" ]; then
    die 'ERROR: Please provide both the DOMAIN and the PORT. Use "wdt --help" to see the help menu.'
else
    # ---------------------------- Installing stuff ---------------------------
    # Install nodejs
    if [ ! -d ~/.n ]; then
        echo "Installing n version manager with node.js LTS..."
        curl -L https://git.io/n-install | N_PREFIX=~/.n bash -s -- -y
        echo "Done"
    else
        echo "[nodejs]: Node is already installed."
    fi

    # Install pm2
    if [ ! -f ~/.n/bin/pm2 ]; then
        echo "Installing pm2, a process manager for node.js..."
        npm install --global pm2
        echo "Done"
    else
        echo "[pm2]: PM2 process manager is already installed."
    fi

    # Install ufw
    if [ ! -f /usr/sbin/ufw ]; then
        echo "Installing ufw -- the Uncomplicated Firewall..."
        sudo apt install ufw -y
        echo "Done"
    else
        echo "[ufw]: Uncomplicated Firewall is already installed."
    fi

    # Install nginx
    if [ ! -f /usr/sbin/nginx ]; then
        echo "Installing nginx..."
        sudo apt install nginx -y
        echo "Done"
    else
        echo "[nginx]: Nginx is already installed."
    fi

    # ---------------------------- Actual commands ----------------------------

    # npm install part
    if [ ! -f ./package.json ]; then
        echo "Initialising npm and Express.js..."
        npm init -y
        npm install express
        echo "Done"
    elif [ ! -d ./node_modules/express ]; then
        echo "Installing Express.js..."
        npm install express
        echo "Done"
    fi

    # UFW
    # check if it's german or english language to get the correct ufw status info
    if [[ $(locale | grep LANG | cut -d= -f2 | cut -d_ -f1) == *"de"* ]]; then
        ufwstatus="Inaktiv"
    elif [[ $(locale | grep LANG | cut -d= -f2 | cut -d_ -f1) == *"en"* ]]; then
        ufwstatus="inactive"
    fi
    # make sure firewall is enabled and allows ssh, http and https
    if sudo ufw status | grep -qw $ufwstatus; then
        echo "[ufw]: Enabling ufw and allowing ssh (22), http (80) and https (443) ports."
        sudo ufw enable
        sudo ufw allow ssh
        sudo ufw allow http
        sudo ufw allow https
    else
        echo "[ufw]: Firewall is enabled Making sure ports 22, 80 and 443 are allowed."
        sudo ufw allow ssh
        sudo ufw allow http
        sudo ufw allow https
    fi

    # Nginx part
    if [ ! -d /var/www/$name/html ]; then

        ####### optional start #######
        # This parts creates the domain folder in /var/www. This isn't necessary,
        # if the user will not store files there. This is still made to do it the
        # correct way and allow user to change their mind and use this folder later
        #######

        # create the directories for the site
        sudo mkdir -p /var/www/$name/html
        # assing the correct ownership
        sudo chown -R $USER:$USER /var/www/$name/html
        # make permissions of our web roots are correct
        sudo chmod -R 755 /var/www
        # creating sample page for the site
        index_html_data="<html>\n\t<head>\n\t\t<title> Welcome to $name! </title>\n\t</head>\n\t<body>\n\t\t<h1> Success! The $name server block is working! </h1>\n\t</body>\n</html>"
        echo -e $index_html_data > /var/www/$name/html/index.html
        ####### optional end #######

        # creating Server Block Files for Each Domain
        nginx_sites_available_file_data="# Virtual Host configuration for $name\n#\nserver {\n\tlisten 80;\n\tlisten [::]:80;\n\n\tserver_name $name www.$name;\n\n\troot /var/www/$name/html;\n\tindex index.html index.htm index.nginx-debian.html;\n\n\tlocation / {\n\t\tproxy_pass http://localhost:$port; # whatever port your app runs on\n\t\tproxy_http_version 1.1;\n\t\tproxy_set_header Upgrade \$http_upgrade;\n\t\tproxy_set_header Connection 'upgrade';\n\t\tproxy_set_header Host \$host;\n\t\tproxy_cache_bypass \$http_upgrade;\n\t}\n}"
        # create new server file and correct it's permissions and ownership
        echo -e $nginx_sites_available_file_data > $name
        sudo mv $name /etc/nginx/sites-available/
        sudo chown -R root:root /etc/nginx/sites-available/$name
        sudo chmod 644 /etc/nginx/sites-available/$name
        # create a symlink to sites-enabled
        sudo ln -s /etc/nginx/sites-available/$name /etc/nginx/sites-enabled/
        # uncomment one line in order to avoid a possible hash bucket memory problem that can arise from adding additional server names
        sudo sed -i "s|# server_names_hash_bucket_size 64;|server_names_hash_bucket_size 64;|g" /etc/nginx/nginx.conf
        # restart nginx
        sudo systemctl restart nginx
    fi

    # Certbot part
    if $enable_ssl; then
        # Install certbot with nginx extension
        if [ ! -f /usr/bin/certbot ]; then
            echo "Installing Certbot from Let's Encrypt with the nginx plugin..."
            sudo apt install python3-certbot-nginx -y
            echo "Done"
        elif [ ! -d /usr/lib/python3/dist-packages/certbot_nginx ]; then
            echo "Installing the nginx plugin for certbot..."
            sudo apt install python3-certbot-nginx -y
            echo "Done"
        else
            echo "[certbot]: Certbot with nginx plugin is already installed."
        fi

        # Enable SSL
        sudo certbot --nginx -d $name -d www.$name
    fi

    # TODO:
    # Crontab part
    if $autorenew_ssl; then
        echo "SSL will be scheduled to autorenew"
    fi
fi
